import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import React, { useCallback } from 'react';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Entypo from '@expo/vector-icons/Entypo';
import { useNavigation } from '@react-navigation/native';

import { useAuth } from '~providers/AuthProvider';
import UserIcon from '~lib/assets/userIcon';
import { APP_COLOR } from '~core/constants/colorConstants';
import getGreeting from '~lib/utils/greetingUtil';
import { FONT_NAMES } from '../core/constants/fontConstants';

const HomeScreen = () => {
  const { top, bottom, left } = useSafeAreaInsets();
  const { logout } = useAuth();
  const navigation = useNavigation();
  const task = [
    {
      amount: 4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 12:17:52',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: true,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: 'USD',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash655AA0A069597C62930BE807F7FC9E5FFD0F8A20',
      transactionID: '4409920264562784684',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: 4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 11:51:15',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash6617F45D8E4E527C4774D5373C7B7F3695AE4108',
      transactionID: '5432334795078220965',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -7000,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-25 13:25:52',
      managedCard: false,
      mcc: 0,
      merchant: 'YUWEN HELLO!',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash29C3E8A6A1846728D3D973A59FDDDD6FF5A5B204',
      transactionID: '37981182973050d23393',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -7000,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: 4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 12:17:52',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: true,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: 'USD',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash655AA0A069597C62930BE807F7FC9E5FFD0F8A20',
      transactionID: '440992026d4562784684',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: 4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 11:51:15',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash6617F45D8E4E527C4774D5373C7B7F3695AE4108',
      transactionID: '54323347950782da20965',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -7000,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-25 13:25:52',
      managedCard: false,
      mcc: 0,
      merchant: 'YUWEN HELLO!',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash29C3E8A6A1846728D3D973A59FDDDD6FF5A5B204',
      transactionID: '3798118cd297305023393',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -7000,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: 4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 12:17:52',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: true,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: 'USD',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash655AA0A069597C62930BE807F7FC9E5FFD0F8A20',
      transactionID: '44099202645627846wwe84',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: 4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 11:51:15',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash6617F45D8E4E527C4774D5373C7B7F3695AE4108',
      transactionID: '543233479507822cs0965',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -7000,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-25 13:25:52',
      managedCard: false,
      mcc: 0,
      merchant: 'YUWEN HELLO!',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash29C3E8A6A1846728D3D973A59FDDDD6FF5A5B204',
      transactionID: '3798118zx297305023393',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -7000,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: 4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 12:17:52',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: true,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: 'USD',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash655AA0A069597C62930BE807F7FC9E5FFD0F8A20',
      transactionID: '44099202645as627846wwe84',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: 4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -4200,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-26 11:51:15',
      managedCard: false,
      mcc: 0,
      merchant: 'Pikachu',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash6617F45D8E4E527C4774D5373C7B7F3695AE4108',
      transactionID: '543233479507822sascs0965',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -4200,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
    {
      amount: -7000,
      bank: '',
      billable: false,
      cardID: 1533948,
      cardName: 'expensifytest@mailinator.com - Cash Expense',
      cardNumber: '',
      category: 'Uncategorized',
      comment: '',
      created: '2999-12-31',
      currency: 'USD',
      details: '',
      externalID: '',
      inserted: '2023-07-25 13:25:52',
      managedCard: false,
      mcc: 0,
      merchant: 'YUWEN HELLO!',
      modified: false,
      modifiedAmount: '',
      modifiedCreated: '',
      modifiedCurrency: '',
      modifiedMCC: '',
      modifiedMerchant: '',
      receiptFilename: '',
      receiptID: '',
      receiptState: 'OPEN',
      reimbursable: false,
      reportID: -1,
      tag: '',
      transactionHash: 'hash29C3E8A6A1846728D3D973A59FDDDD6FF5A5B204',
      transactionID: '3798118zx2asa97305023393',
      nameValuePairs: {
        comment: '',
      },
      unverified: true,
      convertedAmount: -7000,
      currencyConversionRate: 1,
      receiptObject: null,
      editable: 'FULLEDIT',
    },
  ];

  const renderItem = useCallback(
    ({ item }) => (
      <View style={{ backgroundColor: 'red', marginVertical: '2%' }}>
        <View style={styles.item}>
          <Text style={styles.merchant}>{item.merchant}</Text>
          <Text style={styles.amount}>
            {item.currency} {(item.amount / 100).toFixed(2)}
          </Text>
          <Text style={styles.date}>{item.created}</Text>
        </View>
      </View>
    ),
    []
  );
  const listHeader = () => (
    <View style={styles.listHeaderView}>
      <Text style={styles.listHeaderTextTitle}>Transactions</Text>
      <Text
        style={styles.listHeaderTextRedirect}
        onPress={() => navigation.navigate('AllTransactionList')}>
        View all
      </Text>
    </View>
  );
  const keyExtractor = useCallback((item) => item.transactionID, []);

  return (
    <View style={[styles.container, { paddingTop: top, paddingBottom: bottom }]}>
      <Text onPress={() => logout()}>HomeScreen</Text>
      <View style={styles.header}>
        <View style={styles.headerIcon}>
          <UserIcon height={45} width={50} />
        </View>
        <Text style={styles.headerText}>Hello, Good {getGreeting()}</Text>
      </View>
      <Pressable
        style={styles.addTransaction}
        onPress={() => navigation.navigate('AddTransaction')}>
        <Entypo name="circle-with-plus" size={24} color={APP_COLOR.MAIN_GREEN} />
        <Text style={styles.addText}>Add Transaction</Text>
      </Pressable>
      {/* <View style={[styles.transactionView, { paddingBottom: bottom * 5 }]}> */}

      <FlatList
        data={task}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
        initialNumToRender={10}
        maxToRenderPerBatch={20}
        windowSize={21}
        removeClippedSubviews={true}
        ListHeaderComponent={listHeader}
        contentContainerStyle={styles.transactionView}
        showsVerticalScrollIndicator={false}
      />
    </View>
    // </View>
  );
};

export default HomeScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: APP_COLOR.MAIN_WHITE,
    paddingHorizontal: '5%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '1%',
  },
  headerIcon: {
    borderRadius: 50,
    borderWidth: 1,
    borderColor: APP_COLOR.LIGHT_GREY,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: '3%',
    width: 60,
    height: 60,
  },
  headerText: {
    fontFamily: FONT_NAMES.INTER_MEDIUM,
    fontSize: 16,
  },
  addTransaction: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: '4%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
    borderWidth: 0.2,
    borderColor: APP_COLOR.LIGHT_GREY,
    borderRadius: 8,
    backgroundColor: APP_COLOR.MAIN_WHITE,
    marginVertical: '5%',
  },
  addText: {
    fontFamily: FONT_NAMES.INTER_MEDIUM,
    fontSize: 16,
    color: APP_COLOR.MAIN_GREEN,
  },
  transactionView: {
    paddingHorizontal: '5%',
    paddingTop: '4%',
    paddingBottom: '10%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
    borderWidth: 0.2,
    borderColor: APP_COLOR.LIGHT_GREY,
    borderRadius: 8,
    backgroundColor: APP_COLOR.MAIN_WHITE,
    marginTop: '10%',
  },
  listHeaderView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2%',
  },
  listHeaderTextRedirect: {
    fontSize: 16,
    fontFamily: FONT_NAMES.INTER_MEDIUM,
    color: APP_COLOR.MAIN_DARK,
  },
  listHeaderTextTitle: {
    fontSize: 14,
    fontFamily: FONT_NAMES.INTER_REGULAR,
    color: APP_COLOR.LIGHT_GREY,
  },
});
